### PR TITLE
WIP: Add scope to signInFlow

### PR DESCRIPTION
**Pull request by denisemauldin**
Work in Progress commit on adding `scopes` to the github auth request.  I don't know how to upgrade `useCallback` to allow an optional `scope` parameter passed into `signInFlow` or how to pass that into `AuthContext`.  It works if I change:

```
signIn: useCallback(signInFlow(setMe), [setMe]),
```
to
```
signIn: useCallback(signInFlow(setMe, ['repo']), [setMe]),
```

### CODE REVIEW

**Review by curran — COMMENTED** [review]
Looks like a great start!

**Comment by curran** [comment]
@kalpesh05 Do you think you could reconcile this with your recent work? Thanks!

**Comment by kalpesh05** [comment]
Okay I will , but I need understand what is need to accomplish and how much it is progress before dive into it, sorry for asking but may I get more clearance about scopes you want to add because right now we have just added user:email scope only .

**Comment by curran** [comment]
Status of this PR: Let's use it as a reference for when we do eventually dig into building out the GitHub integration.

**Pull request closed without merging**
