### PR TITLE
lift real-time-contexts higher

### PR DESCRIPTION
**Pull request by stushurik**

### CODE REVIEW

**Review by curran — APPROVED** [review]
Looks like a great refactoring! Thanks for this.

**Comment by nitanagdeote** [comment]
What changed here?

**Comment by curran** [comment]
@nitanagdeote It's refactoring that will unblock making more pages real-time enabled. It also unblocks the ability to upvote from previews, which is what @stushurik will be working on after this.

**Comment by nitanagdeote** [comment]
awesome!

**Pull request merged**
